export const countries = [
  { key: "Afghanistan", label: "Afghanistan" },
  { key: "Albania", label: "Albania" },
  { key: "Algeria", label: "Algeria" },
  { key: "Andorra", label: "Andorra" },
  { key: "Angola", label: "Angola" },
  { key: "Antigua and Barbuda", label: "Antigua and Barbuda" },
  { key: "Argentina", label: "Argentina" },
  { key: "Armenia", label: "Armenia" },
  { key: "Australia", label: "Australia" },
  { key: "Austria", label: "Austria" },
  { key: "Azerbaijan", label: "Azerbaijan" },
  { key: "Bahamas", label: "Bahamas" },
  { key: "Bahrain", label: "Bahrain" },
  { key: "Bangladesh", label: "Bangladesh" },
  { key: "Barbados", label: "Barbados" },
  { key: "Belarus", label: "Belarus" },
  { key: "Belgium", label: "Belgium" },
  { key: "Belize", label: "Belize" },
  { key: "Benin", label: "Benin" },
  { key: "Bhutan", label: "Bhutan" },
  { key: "Bolivia", label: "Bolivia" },
  { key: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
  { key: "Botswana", label: "Botswana" },
  { key: "Brazil", label: "Brazil" },
  { key: "Brunei", label: "Brunei" },
  { key: "Bulgaria", label: "Bulgaria" },
  { key: "Burkina Faso", label: "Burkina Faso" },
  { key: "Burundi", label: "Burundi" },
  { key: "Cabo Verde", label: "Cabo Verde" },
  { key: "Cambodia", label: "Cambodia" },
  { key: "Cameroon", label: "Cameroon" },
  { key: "Canada", label: "Canada" },
  { key: "Central African Republic", label: "Central African Republic" },
  { key: "Chad", label: "Chad" },
  { key: "Chile", label: "Chile" },
  { key: "China", label: "China" },
  { key: "Colombia", label: "Colombia" },
  { key: "Comoros", label: "Comoros" },
  { key: "Congo (Congo-Brazzaville)", label: "Congo (Congo-Brazzaville)" },
  { key: "Costa Rica", label: "Costa Rica" },
  { key: "Croatia", label: "Croatia" },
  { key: "Cuba", label: "Cuba" },
  { key: "Cyprus", label: "Cyprus" },
  { key: "Czechia (Czech Republic)", label: "Czechia (Czech Republic)" },
  { key: "Denmark", label: "Denmark" },
  { key: "Djibouti", label: "Djibouti" },
  { key: "Dominica", label: "Dominica" },
  { key: "Dominican Republic", label: "Dominican Republic" },
  { key: "Ecuador", label: "Ecuador" },
  { key: "Egypt", label: "Egypt" },
  { key: "El Salvador", label: "El Salvador" },
  { key: "Equatorial Guinea", label: "Equatorial Guinea" },
  { key: "Eritrea", label: "Eritrea" },
  { key: "Estonia", label: "Estonia" },
  { key: "Eswatini (fmr. Swaziland)", label: "Eswatini (fmr. Swaziland)" },
  { key: "Ethiopia", label: "Ethiopia" },
  { key: "Fiji", label: "Fiji" },
  { key: "Finland", label: "Finland" },
  { key: "France", label: "France" },
  { key: "Gabon", label: "Gabon" },
  { key: "Gambia", label: "Gambia" },
  { key: "Georgia", label: "Georgia" },
  { key: "Germany", label: "Germany" },
  { key: "Ghana", label: "Ghana" },
  { key: "Greece", label: "Greece" },
  { key: "Grenada", label: "Grenada" },
  { key: "Guatemala", label: "Guatemala" },
  { key: "Guinea", label: "Guinea" },
  { key: "Guinea-Bissau", label: "Guinea-Bissau" },
  { key: "Guyana", label: "Guyana" },
  { key: "Haiti", label: "Haiti" },
  { key: "Honduras", label: "Honduras" },
  { key: "Hungary", label: "Hungary" },
  { key: "Iceland", label: "Iceland" },
  { key: "India", label: "India" },
  { key: "Indonesia", label: "Indonesia" },
  { key: "Iran", label: "Iran" },
  { key: "Iraq", label: "Iraq" },
  { key: "Ireland", label: "Ireland" },
  { key: "Israel", label: "Israel" },
  { key: "Italy", label: "Italy" },
  { key: "Jamaica", label: "Jamaica" },
  { key: "Japan", label: "Japan" },
  { key: "Jordan", label: "Jordan" },
  { key: "Kazakhstan", label: "Kazakhstan" },
  { key: "Kenya", label: "Kenya" },
  { key: "Kiribati", label: "Kiribati" },
  { key: "Korea, North", label: "Korea, North" },
  { key: "Korea, South", label: "Korea, South" },
  { key: "Kosovo", label: "Kosovo" },
  { key: "Kuwait", label: "Kuwait" },
  { key: "Kyrgyzstan", label: "Kyrgyzstan" },
  { key: "Laos", label: "Laos" },
  { key: "Latvia", label: "Latvia" },
  { key: "Lebanon", label: "Lebanon" },
  { key: "Lesotho", label: "Lesotho" },
  { key: "Liberia", label: "Liberia" },
  { key: "Libya", label: "Libya" },
  { key: "Liechtenstein", label: "Liechtenstein" },
  { key: "Lithuania", label: "Lithuania" },
  { key: "Luxembourg", label: "Luxembourg" },
  { key: "Madagascar", label: "Madagascar" },
  { key: "Malawi", label: "Malawi" },
  { key: "Malaysia", label: "Malaysia" },
  { key: "Maldives", label: "Maldives" },
  { key: "Mali", label: "Mali" },
  { key: "Malta", label: "Malta" },
  { key: "Marshall Islands", label: "Marshall Islands" },
  { key: "Mauritania", label: "Mauritania" },
  { key: "Mauritius", label: "Mauritius" },
  { key: "Mexico", label: "Mexico" },
  { key: "Micronesia", label: "Micronesia" },
  { key: "Moldova", label: "Moldova" },
  { key: "Monaco", label: "Monaco" },
  { key: "Mongolia", label: "Mongolia" },
  { key: "Montenegro", label: "Montenegro" },
  { key: "Morocco", label: "Morocco" },
  { key: "Mozambique", label: "Mozambique" },
  { key: "Myanmar (formerly Burma)", label: "Myanmar (formerly Burma)" },
  { key: "Namibia", label: "Namibia" },
  { key: "Nauru", label: "Nauru" },
  { key: "Nepal", label: "Nepal" },
  { key: "Netherlands", label: "Netherlands" },
  { key: "New Zealand", label: "New Zealand" },
  { key: "Nicaragua", label: "Nicaragua" },
  { key: "Niger", label: "Niger" },
  { key: "Nigeria", label: "Nigeria" },
  { key: "North Macedonia", label: "North Macedonia" },
  { key: "Norway", label: "Norway" },
  { key: "Oman", label: "Oman" },
  { key: "Pakistan", label: "Pakistan" },
  { key: "Palau", label: "Palau" },
  { key: "Panama", label: "Panama" },
  { key: "Papua New Guinea", label: "Papua New Guinea" },
  { key: "Paraguay", label: "Paraguay" },
  { key: "Peru", label: "Peru" },
  { key: "Philippines", label: "Philippines" },
  { key: "Poland", label: "Poland" },
  { key: "Portugal", label: "Portugal" },
  { key: "Qatar", label: "Qatar" },
  { key: "Romania", label: "Romania" },
  { key: "Russia", label: "Russia" },
  { key: "Rwanda", label: "Rwanda" },
  { key: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis" },
  { key: "Saint Lucia", label: "Saint Lucia" },
  {
    key: "Saint Vincent and the Grenadines",
    label: "Saint Vincent and the Grenadines",
  },
  { key: "Samoa", label: "Samoa" },
  { key: "San Marino", label: "San Marino" },
  { key: "Sao Tome and Principe", label: "Sao Tome and Principe" },
  { key: "Saudi Arabia", label: "Saudi Arabia" },
  { key: "Senegal", label: "Senegal" },
  { key: "Serbia", label: "Serbia" },
  { key: "Seychelles", label: "Seychelles" },
  { key: "Sierra Leone", label: "Sierra Leone" },
  { key: "Singapore", label: "Singapore" },
  { key: "Slovakia", label: "Slovakia" },
  { key: "Slovenia", label: "Slovenia" },
  { key: "Solomon Islands", label: "Solomon Islands" },
  { key: "Somalia", label: "Somalia" },
  { key: "South Africa", label: "South Africa" },
  { key: "South Sudan", label: "South Sudan" },
  { key: "Spain", label: "Spain" },
  { key: "Sri Lanka", label: "Sri Lanka" },
  { key: "Sudan", label: "Sudan" },
  { key: "Suriname", label: "Suriname" },
  { key: "Sweden", label: "Sweden" },
  { key: "Switzerland", label: "Switzerland" },
  { key: "Syria", label: "Syria" },
  { key: "Taiwan", label: "Taiwan" },
  { key: "Tajikistan", label: "Tajikistan" },
  { key: "Tanzania", label: "Tanzania" },
  { key: "Thailand", label: "Thailand" },
  { key: "Timor-Leste", label: "Timor-Leste" },
  { key: "Togo", label: "Togo" },
  { key: "Tonga", label: "Tonga" },
  { key: "Trinidad and Tobago", label: "Trinidad and Tobago" },
  { key: "Tunisia", label: "Tunisia" },
  { key: "Turkey", label: "Turkey" },
  { key: "Turkmenistan", label: "Turkmenistan" },
  { key: "Tuvalu", label: "Tuvalu" },
  { key: "Uganda", label: "Uganda" },
  { key: "Ukraine", label: "Ukraine" },
  { key: "United Arab Emirates", label: "United Arab Emirates" },
  { key: "United Kingdom", label: "United Kingdom" },
  { key: "United States of America", label: "United States of America" },
  { key: "Uruguay", label: "Uruguay" },
  { key: "Uzbekistan", label: "Uzbekistan" },
  { key: "Vanuatu", label: "Vanuatu" },
  { key: "Vatican City", label: "Vatican City" },
  { key: "Venezuela", label: "Venezuela" },
  { key: "Vietnam", label: "Vietnam" },
  { key: "Yemen", label: "Yemen" },
  { key: "Zambia", label: "Zambia" },
  { key: "Zimbabwe", label: "Zimbabwe" },
];

export const installmentOptions = [
  // { key: "", label: "Select installments" },
  { key: "1", label: "1 (Pay in full)", forAge: 22 },
  { key: "2", label: "2 Installments", forAge: 20 },
  { key: "4", label: "4 Installments", forAge: 19 },
  { key: "6", label: "6 Installments", forAge: 18 },
  { key: "8", label: "8 Installments", forAge: 17 },
  { key: "10", label: "10 Installments", forAge: 16 },
  { key: "12", label: "12 Installments", forAge: 15 },
  { key: "14", label: "14 Installments", forAge: 14 },
  { key: "16", label: "16 Installments", forAge: 13 },
  { key: "18", label: "18 Installments", forAge: 12 },
  { key: "20", label: "20 Installments", forAge: 11 },
  { key: "22", label: "22 Installments", forAge: 10 },
  { key: "24", label: "24 Installments", forAge: 10 },
  { key: "26", label: "26 Installments", forAge: 10 },
  { key: "28", label: "28 Installments", forAge: 10 },
  { key: "30", label: "30 Installments", forAge: 10 },
  { key: "32", label: "32 Installments", forAge: 10 },
];

export const installmentStatus = [
  { id: "Pending", label: "Pending" },
  { id: "Paid", label: "Paid" },
  // { key: "Cancelled", label: "Cancelled" },
];
